
INSERT INTO "DEMO"."COURSE" (COURSE_ID,COURSE_NAME) VALUES (1,'Some Course');
INSERT INTO "DEMO"."COURSE" (COURSE_ID,COURSE_NAME) VALUES (2,'Another Course');

INSERT INTO "DEMO"."STUDENT" (STUDENT_ID,LAST_NAME) VALUES (1,'Student1');
INSERT INTO "DEMO"."STUDENT" (STUDENT_ID,LAST_NAME) VALUES (2,'Student2');
INSERT INTO "DEMO"."STUDENT" (STUDENT_ID,LAST_NAME) VALUES (3,'Student3');

INSERT INTO "DEMO"."STUDENT_COURSE" (STUDENT_ID,COURSE_ID) VALUES (1,1);
INSERT INTO "DEMO"."STUDENT_COURSE" (STUDENT_ID,COURSE_ID) VALUES (1,2);
INSERT INTO "DEMO"."STUDENT_COURSE" (STUDENT_ID,COURSE_ID) VALUES (2,1);
INSERT INTO "DEMO"."STUDENT_COURSE" (STUDENT_ID,COURSE_ID) VALUES (3,2);

